"""Item boxes, handles, drags, snapping and safe areas.

A port of `ui/kits/canvas/geometry.js`, `gizmos.js`, `snap.js` and `safe.js`.
It is arithmetic and nothing else: no `tkinter` import anywhere, because a
headless script has to be able to import it and because the test suite replays
`ui/kits/fixtures.json` through it with no display.

Boxes are dictionaries with `x`, `y`, `width` and `height`, in canvas pixels,
the same keys the JavaScript uses. Transforms are the document's own shape:
`{"position": {...}, "frame": {...}, "scale": {...}, "anchor": {...}}`.

The one piece of scene arithmetic a client is allowed to do for itself is the
reverse map, because a drag produces a rectangle and the document wants a
transform. Everything else comes from the core: every mutating command answers
with the flattened geometry, so a client never recomputes a layout and never
disagrees with the compositor about where an item is.
"""

from __future__ import annotations

import math
from typing import Any, Dict, List, Optional, Sequence, Tuple


# ----------------------------------------------------------------- numbers


def _n(value: Any, fallback: float = 0.0) -> float:
    """What `Number(x)` gives, with a NaN or an infinity treated as absent."""
    if isinstance(value, bool) or value is None:
        return fallback
    try:
        out = float(value)
    except (TypeError, ValueError):
        return fallback
    if math.isnan(out) or math.isinf(out):
        return fallback
    return out


def _js_round(value: float) -> int:
    """`Math.round`: halves go up, which Python's own `round` does not do.

    Python rounds a half to the even neighbour. The fixtures were generated by
    the reference implementation in JavaScript, so the ports have to round the
    way it does or a handle lands a pixel out once every few drags.
    """
    return math.floor(value + 0.5)


def _round(value: float, places: int) -> float:
    factor = 10 ** places
    return _js_round(value * factor) / factor


def _clamp(value: float, low: float, high: float) -> float:
    return min(high, max(low, value))


def _sign(value: float) -> int:
    return -1 if value < 0 else (1 if value > 0 else 0)


# ---------------------------------------------------------------- geometry


def item_rect(transform: Optional[Dict[str, Any]], canvas: Dict[str, Any]) -> Dict[str, float]:
    """The box an item occupies, before rotation, from its transform.

    This is `geometry.rs::item_rect` written out once, which is why the handles
    land on the picture in all three kits::

        x = position.x - anchor.x * (frame.w * scale.x)
    """
    t = transform or {}
    frame = t.get("frame") or {"w": canvas["width"], "h": canvas["height"]}
    scale = t.get("scale") or {"x": 1, "y": 1}
    anchor = t.get("anchor") or {"x": 0, "y": 0}
    position = t.get("position") or {}
    width = _n(frame.get("w"), canvas["width"]) * _n(scale.get("x"), 1)
    height = _n(frame.get("h"), canvas["height"]) * _n(scale.get("y"), 1)
    return {
        "x": _n(position.get("x")) - _n(anchor.get("x")) * width,
        "y": _n(position.get("y")) - _n(anchor.get("y")) * height,
        "width": width,
        "height": height,
    }


def rect_to_transform(rect: Dict[str, float], transform: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """The transform a rectangle asks for, keeping the item's anchor and scale."""
    t = transform or {}
    scale = t.get("scale") or {"x": 1, "y": 1}
    anchor = t.get("anchor") or {"x": 0, "y": 0}
    return {
        "frame": {
            "w": rect["width"] / (_n(scale.get("x"), 1) or 1),
            "h": rect["height"] / (_n(scale.get("y"), 1) or 1),
        },
        "position": {
            "x": rect["x"] + _n(anchor.get("x")) * rect["width"],
            "y": rect["y"] + _n(anchor.get("y")) * rect["height"],
        },
    }


def overlaps(a: Dict[str, float], b: Dict[str, float]) -> bool:
    """Do two boxes touch?"""
    return (
        a["x"] < b["x"] + b["width"]
        and b["x"] < a["x"] + a["width"]
        and a["y"] < b["y"] + b["height"]
        and b["y"] < a["y"] + a["height"]
    )


def inside(box: Dict[str, float], x: float, y: float) -> bool:
    """Is a point inside a box?"""
    return box["x"] <= x <= box["x"] + box["width"] and box["y"] <= y <= box["y"] + box["height"]


def rect_from(x0: float, y0: float, x1: float, y1: float) -> Dict[str, float]:
    """Normalise a sweep from its two corners, so dragging up and left works."""
    return {"x": min(x0, x1), "y": min(y0, y1), "width": abs(x1 - x0), "height": abs(y1 - y0)}


def union_of(boxes: Optional[Sequence[Dict[str, float]]]) -> Optional[Dict[str, float]]:
    """The smallest box round a set of boxes, or None for none."""
    if not boxes:
        return None
    x0 = min(b["x"] for b in boxes)
    y0 = min(b["y"] for b in boxes)
    x1 = max(b["x"] + b["width"] for b in boxes)
    y1 = max(b["y"] + b["height"] for b in boxes)
    return {"x": x0, "y": y0, "width": x1 - x0, "height": y1 - y0}


class View:
    """Canvas pixels to the surface the preview is drawn on, and back.

    The preview picture is whatever size the window gave it; the document is in
    canvas pixels. One object holds the two, so nothing else in a designer
    multiplies by a ratio and gets it wrong in one place out of five.
    """

    def __init__(self, canvas: Optional[Dict[str, Any]] = None, surface: Optional[Dict[str, Any]] = None):
        self.set(canvas, surface)

    def set(self, canvas: Optional[Dict[str, Any]], surface: Optional[Dict[str, Any]]) -> "View":
        self.canvas = canvas or {"width": 1920, "height": 1080}
        self.surface = surface or {"width": 1, "height": 1}
        # The picture is letterboxed inside the surface, the way `object-fit:
        # contain` draws it, so the handles sit on the picture and not beside
        # it.
        try:
            scale = min(
                self.surface["width"] / self.canvas["width"],
                self.surface["height"] / self.canvas["height"],
            )
        except ZeroDivisionError:
            scale = 0.0
        self.scale = scale if math.isfinite(scale) and scale > 0 else 1.0
        self.offset_x = (self.surface["width"] - self.canvas["width"] * self.scale) / 2
        self.offset_y = (self.surface["height"] - self.canvas["height"] * self.scale) / 2
        return self

    def to_surface(self, x: float, y: float) -> Tuple[float, float]:
        return (self.offset_x + x * self.scale, self.offset_y + y * self.scale)

    def to_canvas(self, x: float, y: float) -> Tuple[float, float]:
        return ((x - self.offset_x) / self.scale, (y - self.offset_y) / self.scale)

    def box_to_surface(self, box: Dict[str, float]) -> Dict[str, float]:
        x, y = self.to_surface(box["x"], box["y"])
        return {"x": x, "y": y, "width": box["width"] * self.scale, "height": box["height"] * self.scale}

    def length_from_surface(self, pixels: float) -> float:
        """A length in canvas pixels that draws as `pixels` on the surface."""
        return pixels / self.scale


# ------------------------------------------------------------------ gizmos
#
# A plugin says what handles its item type has and what each one drives, in its
# manifest, as data::
#
#     [provides.designer]
#     gizmos = ["corner", "rotate"]
#
# Nothing in that is code, which is the point: a Tkinter designer draws the same
# handles as the web composer from the same manifest, and both send back a named
# command rather than a coordinate. The anchor is normalised about the item's
# centre: (-0.5, -0.5) is the top left corner, (0, -0.6) is above the top edge.
# That survives a canvas change and a resize, which pixels do not.

#: What an item gets when its plugin says nothing: move, scale, rotate.
DEFAULT_GIZMOS: List[Dict[str, Any]] = [
    {"kind": "cage", "anchor": [0, 0], "action": "move", "target": "transform.position"},
    {"kind": "corner", "anchor": [-0.5, -0.5], "action": "scale", "target": "transform.frame"},
    {"kind": "corner", "anchor": [0.5, -0.5], "action": "scale", "target": "transform.frame"},
    {"kind": "corner", "anchor": [-0.5, 0.5], "action": "scale", "target": "transform.frame"},
    {"kind": "corner", "anchor": [0.5, 0.5], "action": "scale", "target": "transform.frame"},
    {"kind": "edge", "anchor": [0, -0.5], "action": "scale", "target": "transform.frame"},
    {"kind": "edge", "anchor": [0, 0.5], "action": "scale", "target": "transform.frame"},
    {"kind": "edge", "anchor": [-0.5, 0], "action": "scale", "target": "transform.frame"},
    {"kind": "edge", "anchor": [0.5, 0], "action": "scale", "target": "transform.frame"},
    {"kind": "rotate", "anchor": [0, -0.62], "action": "rotate", "target": "transform.rotation"},
]

#: The cursor each direction wants, so a corner says what it will do.
CURSORS = {
    (-1, -1): "nwse-resize",
    (1, 1): "nwse-resize",
    (1, -1): "nesw-resize",
    (-1, 1): "nesw-resize",
    (0, -1): "ns-resize",
    (0, 1): "ns-resize",
    (-1, 0): "ew-resize",
    (1, 0): "ew-resize",
}

def _copy(gizmos: Sequence[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Each archetype owns its gizmos, rather than sharing DEFAULT_GIZMOS'.

    A caller that reads an archetype and nudges an anchor should not find the
    defaults changed underneath it, which is what sharing the dictionaries
    would do.
    """
    return [dict(g, anchor=list(g["anchor"])) for g in gizmos]


#: The named archetypes, for the short spelling a manifest usually wants.
ARCHETYPES: Dict[str, List[Dict[str, Any]]] = {
    "cage": _copy(DEFAULT_GIZMOS[0:1]),
    "move": _copy(DEFAULT_GIZMOS[0:1]),
    "corner": _copy(DEFAULT_GIZMOS[1:5]),
    "edge": _copy(DEFAULT_GIZMOS[5:9]),
    "scale": _copy(DEFAULT_GIZMOS[1:9]),
    "rotate": _copy(DEFAULT_GIZMOS[9:10]),
    "crop": [
        {"kind": "edge", "anchor": [-0.5, 0], "action": "crop", "target": "crop.left"},
        {"kind": "edge", "anchor": [0.5, 0], "action": "crop", "target": "crop.right"},
        {"kind": "edge", "anchor": [0, -0.5], "action": "crop", "target": "crop.top"},
        {"kind": "edge", "anchor": [0, 0.5], "action": "crop", "target": "crop.bottom"},
    ],
}


def _valid_gizmo(entry: Any) -> bool:
    return (
        isinstance(entry, dict)
        and isinstance(entry.get("kind"), str)
        and isinstance(entry.get("anchor"), (list, tuple))
        and len(entry["anchor"]) == 2
    )


def gizmos_for(designer: Optional[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """The gizmos for one item type: the plugin's, or the defaults.

    Never empty, because an item with no handles cannot be edited at all, which
    is the one outcome 11 section 5 rules out. A plugin that declares handles
    still gets a cage: without one nothing could pick the item up, and no
    plugin author should have to remember that.
    """
    declared: List[Dict[str, Any]] = []
    for entry in (designer or {}).get("gizmos") or []:
        if isinstance(entry, str):
            declared.extend(ARCHETYPES.get(entry) or [])
        elif _valid_gizmo(entry):
            declared.append(entry)
    if not declared:
        return DEFAULT_GIZMOS
    if any(g.get("kind") == "cage" for g in declared):
        return declared
    return [DEFAULT_GIZMOS[0]] + declared


def handles_for(box: Dict[str, float], gizmos: Sequence[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Where each handle sits, in canvas pixels, for one item's box."""
    cx = box["x"] + box["width"] / 2
    cy = box["y"] + box["height"] / 2
    out: List[Dict[str, Any]] = []
    for index, gizmo in enumerate(gizmos or []):
        nx, ny = gizmo["anchor"]
        direction = [_sign(nx), _sign(ny)]
        fallback = "grab" if gizmo["kind"] == "rotate" else "move"
        out.append(
            {
                "i": index,
                "kind": gizmo["kind"],
                "action": gizmo.get("action") or "move",
                "target": gizmo.get("target") or "transform.position",
                "x": cx + nx * box["width"],
                "y": cy + ny * box["height"],
                "dir": direction,
                "cursor": gizmo.get("cursor") or CURSORS.get((direction[0], direction[1])) or fallback,
            }
        )
    return out


def hit_test(
    handles: Sequence[Dict[str, Any]],
    x: float,
    y: float,
    radius: float,
) -> Optional[Dict[str, Any]]:
    """The handle under a point, nearest first, or None. `radius` is canvas pixels."""
    best = None
    best_distance = radius * radius
    for handle in handles:
        if handle["kind"] == "cage":
            continue
        distance = (handle["x"] - x) ** 2 + (handle["y"] - y) ** 2
        if distance <= best_distance:
            best_distance = distance
            best = handle
    return best


def apply_drag(
    handle: Dict[str, Any],
    start: Dict[str, Any],
    dx: float,
    dy: float,
    mods: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """A drag on one handle, as the props to assign.

    Pure arithmetic: it is handed where the item is and where the pointer went,
    and it answers with `props` for `scene.item.set` and the `box` to draw while
    the core catches up. No widget, no client, no state, so the Python and the
    TypeScript ports are the same function and the fixtures check all three.

    `start` is `{"box": ..., "transform": ...}` as they were when the drag
    began. `mods` carries what the keyboard is saying: `aspect` for Shift,
    `centre` for Alt, and `pointer`, `min`, `max`, `from` and `step` for the
    handles that want them.
    """
    mods = mods or {}
    box = start["box"]
    transform = start.get("transform") or {}
    action = handle.get("action")
    if action == "scale":
        return _scaled(handle, box, transform, dx, dy, mods)
    if action == "crop":
        return _cropped(handle, box, transform, dx, dy)
    if action == "rotate":
        return _rotated(handle, box, mods)
    if action == "set":
        return _dialled(handle, dx, mods)
    return _moved(box, transform, dx, dy)


def _moved(box: Dict[str, float], t: Dict[str, Any], dx: float, dy: float) -> Dict[str, Any]:
    position = t.get("position") or {}
    moved = {"x": _n(position.get("x")) + dx, "y": _n(position.get("y")) + dy}
    out_box = dict(box)
    out_box["x"] = box["x"] + dx
    out_box["y"] = box["y"] + dy
    return {"props": {"transform": {"position": moved}}, "box": out_box}


def _scaled(
    handle: Dict[str, Any],
    box: Dict[str, float],
    t: Dict[str, Any],
    dx: float,
    dy: float,
    mods: Dict[str, Any],
) -> Dict[str, Any]:
    """A corner or an edge.

    The opposite side stays where it is, which is what every drawing program
    does and what a person expects when they pull a corner.
    """
    sx, sy = handle["dir"]
    both = 2 if mods.get("centre") else 1
    width = box["width"] + sx * dx * both
    height = box["height"] + sy * dy * both
    if mods.get("aspect") and box["width"] > 0 and box["height"] > 0 and sx != 0 and sy != 0:
        # Shift keeps the shape: the larger change wins so the box follows the
        # hand rather than the axis it happened to start on.
        ratio = box["width"] / box["height"]
        if abs(width / ratio - box["height"]) > abs(height - box["height"]):
            height = width / ratio
        else:
            width = height * ratio
    width = max(16, width)
    height = max(16, height)
    x = box["x"]
    y = box["y"]
    if mods.get("centre"):
        x = box["x"] + (box["width"] - width) / 2
        y = box["y"] + (box["height"] - height) / 2
    else:
        if sx < 0:
            x = box["x"] + (box["width"] - width)
        if sy < 0:
            y = box["y"] + (box["height"] - height)
    scale = t.get("scale") or {"x": 1, "y": 1}
    anchor = t.get("anchor") or {"x": 0, "y": 0}
    frame = {"w": width / (_n(scale.get("x"), 1) or 1), "h": height / (_n(scale.get("y"), 1) or 1)}
    position = {"x": x + _n(anchor.get("x")) * width, "y": y + _n(anchor.get("y")) * height}
    out_box = dict(box)
    out_box.update({"x": x, "y": y, "width": width, "height": height})
    return {"props": {"transform": {"frame": frame, "position": position}}, "box": out_box}


#: A crop side and the side opposite it, for the clamp.
_OPPOSITE = {"left": "right", "right": "left", "top": "bottom", "bottom": "top"}


def _cropped(
    handle: Dict[str, Any],
    box: Dict[str, float],
    t: Dict[str, Any],
    dx: float,
    dy: float,
) -> Dict[str, Any]:
    """Crop is normalised 0 to 1 of the content's own pixels, not canvas pixels.

    That is what makes it survive a canvas change. vMix and CasparCG do it this
    way; OBS crops in pixels and loses them at 720p.
    """
    side = str(handle.get("target") or "").split(".")[-1]
    crop = {"left": 0, "top": 0, "right": 0, "bottom": 0}
    crop.update(t.get("crop") or {})
    if side in ("left", "right"):
        along = dx / max(1, box["width"])
    else:
        along = dy / max(1, box["height"])
    sign = -1 if side in ("right", "bottom") else 1
    other = _OPPOSITE.get(side)
    ceiling = 0.95 - _n(crop.get(other) if other else None)
    crop[side] = _clamp(_n(crop.get(side)) + along * sign, 0, ceiling)
    return {"props": {"crop": crop}, "box": box}


def _rotated(handle: Dict[str, Any], box: Dict[str, float], mods: Dict[str, Any]) -> Dict[str, Any]:
    """Degrees clockwise about the item's centre, snapped to 15 with Shift.

    The angle is read from where the pointer is, not from how far it travelled:
    a rotation handle that integrates deltas drifts over a long drag.
    """
    cx = box["x"] + box["width"] / 2
    cy = box["y"] + box["height"] / 2
    pointer = mods.get("pointer") or {"x": handle.get("x", 0), "y": handle.get("y", 0)}
    at = math.atan2(_n(pointer.get("y")) - cy, _n(pointer.get("x")) - cx) * (180 / math.pi) + 90
    degrees = _js_round(at / 15) * 15 if mods.get("aspect") else at
    degrees = ((degrees % 360) + 360) % 360
    return {"props": {"transform": {"rotation": _round(degrees, 2)}}, "box": box}


def _dialled(handle: Dict[str, Any], dx: float, mods: Dict[str, Any]) -> Dict[str, Any]:
    """A dial: sideways travel is the number.

    The plugin's schema says what the ends are. Without one, 0 to 1 over 200
    pixels, which is what a person expects of a knob they have never seen.
    """
    low = 0 if mods.get("min") is None else mods["min"]
    high = 1 if mods.get("max") is None else mods["max"]
    start = low if mods.get("from") is None else mods["from"]
    span = (high - low) / 200
    value = _clamp(start + dx * span, low, high)
    if mods.get("step"):
        value = _js_round(value / mods["step"]) * mods["step"]
    return {"props": path_props(handle.get("target"), _round(value, 4)), "box": None}


def path_props(path: Optional[str], value: Any) -> Dict[str, Any]:
    """`params.key_tolerance` becomes `{"params": {"key_tolerance": value}}`."""
    parts = [p for p in str(path or "").split(".") if p]
    if not parts:
        return {}
    out: Dict[str, Any] = {}
    at = out
    for part in parts[:-1]:
        at[part] = {}
        at = at[part]
    at[parts[-1]] = value
    return out


def path_value(obj: Any, path: Optional[str]) -> Any:
    """Read `transform.frame.w` out of an object, or None."""
    at = obj
    for part in [p for p in str(path or "").split(".") if p]:
        if not isinstance(at, dict):
            return None
        at = at.get(part)
    return at


# ------------------------------------------------------------------ snapping
#
# Split the way tldraw splits it (11 section 5). The plugin answers with
# geometry: `snap = { bounds = true, points = ["params.anchor_point"] }` says
# this item type snaps by its box and by one named point of its own. The client
# owns everything else: the threshold, the modifier that turns snapping off, the
# grid, and the drawing of the guides. That division is why a plugin author
# never tunes a pixel and why a Pi can use a wider threshold than a workstation
# without asking anybody.

#: How close, in canvas pixels, before an edge is taken as lined up.
THRESHOLD = 8


def snap_targets(what: Dict[str, Any]) -> Dict[str, List[Dict[str, Any]]]:
    """Every line a moving box could line up with.

    `what` carries `canvas`, `boxes` and, when a plugin named any, `points`.
    The answer is `{"v": [...], "h": [...]}`, each entry `{"at", "span"}`.
    """
    vertical: List[Dict[str, Any]] = []
    horizontal: List[Dict[str, Any]] = []
    canvas = what.get("canvas")
    if canvas:
        # The canvas edges and its two centre lines, which is what most items
        # are actually being lined up against.
        _push(vertical, 0, [0, canvas["height"]])
        _push(vertical, canvas["width"] / 2, [0, canvas["height"]])
        _push(vertical, canvas["width"], [0, canvas["height"]])
        _push(horizontal, 0, [0, canvas["width"]])
        _push(horizontal, canvas["height"] / 2, [0, canvas["width"]])
        _push(horizontal, canvas["height"], [0, canvas["width"]])
    for box in what.get("boxes") or []:
        down = [box["y"], box["y"] + box["height"]]
        _push(vertical, box["x"], down)
        _push(vertical, box["x"] + box["width"] / 2, down)
        _push(vertical, box["x"] + box["width"], down)
        across = [box["x"], box["x"] + box["width"]]
        _push(horizontal, box["y"], across)
        _push(horizontal, box["y"] + box["height"] / 2, across)
        _push(horizontal, box["y"] + box["height"], across)
    for point in what.get("points") or []:
        _push(vertical, point["x"], [point["y"] - 40, point["y"] + 40])
        _push(horizontal, point["y"], [point["x"] - 40, point["x"] + 40])
    return {"v": vertical, "h": horizontal}


def _push(targets: List[Dict[str, Any]], at: float, span: Sequence[float]) -> None:
    if not math.isfinite(at):
        return
    for had in targets:
        if abs(had["at"] - at) < 0.01:
            had["span"] = [min(had["span"][0], span[0]), max(had["span"][1], span[1])]
            return
    targets.append({"at": at, "span": [span[0], span[1]]})


def snap_delta(
    box: Dict[str, float],
    targets: Dict[str, List[Dict[str, Any]]],
    opts: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """How far to nudge a box so it lines up, and what to draw while it does.

    `invert` is the modifier held: snapping is on by default and the modifier
    turns it off, which is the way every drawing program does it and the way a
    person discovers it by accident rather than by reading.
    """
    opts = opts or {}
    out: Dict[str, Any] = {"dx": 0, "dy": 0, "guides": []}
    if opts.get("invert"):
        return out
    threshold = THRESHOLD if opts.get("threshold") is None else opts["threshold"]

    down = [box["x"], box["x"] + box["width"] / 2, box["x"] + box["width"]]
    across = [box["y"], box["y"] + box["height"] / 2, box["y"] + box["height"]]

    best_v = _nearest(down, targets.get("v"), threshold)
    best_h = _nearest(across, targets.get("h"), threshold)
    if best_v:
        out["dx"] = best_v["delta"]
        span = _grown(best_v["target"]["span"], [box["y"], box["y"] + box["height"]])
        out["guides"].append({"axis": "v", "at": best_v["target"]["at"], "span": span})
    if best_h:
        out["dy"] = best_h["delta"]
        span = _grown(best_h["target"]["span"], [box["x"], box["x"] + box["width"]])
        out["guides"].append({"axis": "h", "at": best_h["target"]["at"], "span": span})
    grid = opts.get("grid")
    if grid and not best_v:
        out["dx"] = _js_round(box["x"] / grid) * grid - box["x"]
    if grid and not best_h:
        out["dy"] = _js_round(box["y"] / grid) * grid - box["y"]
    return out


def _nearest(
    edges: Sequence[float],
    targets: Optional[Sequence[Dict[str, Any]]],
    threshold: float,
) -> Optional[Dict[str, Any]]:
    best = None
    for edge in edges:
        for target in targets or []:
            delta = target["at"] - edge
            if abs(delta) > threshold:
                continue
            if best is None or abs(delta) < abs(best["delta"]):
                best = {"delta": delta, "target": target}
    return best


def _grown(span: Sequence[float], other: Sequence[float]) -> List[float]:
    return [min(span[0], other[0]), max(span[1], other[1])]


def points_of(
    item: Dict[str, Any],
    box: Dict[str, float],
    snap: Optional[Dict[str, Any]],
) -> List[Dict[str, float]]:
    """The points a plugin's `snap.points` names, resolved against one item.

    A point is normalised within the item's own box, because a plugin knows its
    anchor as a fraction and knows nothing about the canvas.
    """
    out: List[Dict[str, float]] = []
    for path in (snap or {}).get("points") or []:
        value = path_value(item, path)
        if not isinstance(value, dict):
            continue
        x = _n(value.get("x"), math.nan)
        y = _n(value.get("y"), math.nan)
        if math.isnan(x) or math.isnan(y):
            continue
        out.append({"x": box["x"] + x * box["width"], "y": box["y"] + y * box["height"]})
    return out


# --------------------------------------------------------------- safe areas
#
# The same two numbers the core's validator uses (`validate.rs`): action safe is
# the middle 93 percent, title safe the middle 90. Drawing them with different
# numbers from the ones `scene.validate` warns about would be worse than not
# drawing them at all.

ACTION_SAFE = 0.07
TITLE_SAFE = 0.1


def inset_fraction(box: Dict[str, float], fraction: float) -> Dict[str, float]:
    """Shrink a box towards its centre by a fraction of each side."""
    dx = (box["width"] * fraction) / 2
    dy = (box["height"] * fraction) / 2
    return {
        "x": box["x"] + dx,
        "y": box["y"] + dy,
        "width": box["width"] - dx * 2,
        "height": box["height"] - dy * 2,
    }


def safe_areas(canvas: Dict[str, Any]) -> Dict[str, Dict[str, float]]:
    """The two rectangles a designer draws over the picture, in canvas pixels."""
    full = {"x": 0, "y": 0, "width": canvas["width"], "height": canvas["height"]}
    return {"action": inset_fraction(full, ACTION_SAFE), "title": inset_fraction(full, TITLE_SAFE)}


def ticks(length: float, scale: float, wanted: float = 80) -> List[int]:
    """Ruler ticks along one axis, at a spacing a person reads.

    About one tick per 80 screen pixels, rounded to 10, 20, 50, 100 and so on,
    so the numbers stay legible at any zoom.
    """
    raw = wanted / (scale or 1)
    power = 10 ** math.floor(math.log10(max(1, raw)))
    step = next((m * power for m in (1, 2, 5, 10) if m * power >= raw), power * 10)
    out: List[int] = []
    at = 0.0
    while at <= length + 0.5:
        out.append(_js_round(at))
        at += step
    return out
