#!/usr/bin/env python3
"""Write compatibility.md out of index.json.

The dashboard is the public answer to one question: will this plugin run on
the core I have, on the machine I have, and did anybody check. Everything it
prints is already in index.json, written there by the listing workflow after
it built and tested each release. Nothing here talks to the network and
nothing here judges a listing; bot/validate.py does the judging.

    python3 bot/dashboard.py            rewrite compatibility.md
    python3 bot/dashboard.py --check    fail if the file on disk is stale

The second form is what CI runs, so a hand edited dashboard is caught in the
pull request that edited it.
"""

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DEFAULT_INDEX = os.path.join(ROOT, "index.json")
DEFAULT_OUT = os.path.join(ROOT, "compatibility.md")

PLATFORMS = [
    "linux-x86_64",
    "linux-aarch64",
    "linux-armv7",
    "macos-aarch64",
    "macos-x86_64",
    "windows-x86_64",
    "windows-aarch64",
]

TIERS = ["custom", "bronze", "silver", "gold"]

GENERATED = "<!-- Generated by bot/dashboard.py from index.json. Do not edit by hand. -->"


# ---------------------------------------------------------------------------
# Reading
# ---------------------------------------------------------------------------


def load(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def sorted_plugins(doc):
    """Highest tier first, then by name, the order the core's search uses."""
    def key(entry):
        tier = entry.get("tier", "custom")
        rank = TIERS.index(tier) if tier in TIERS else 0
        return (-rank, entry.get("name", ""))

    return sorted(doc.get("plugins", []), key=key)


def newest(entry):
    versions = entry.get("versions") or []
    return versions[-1] if versions else None


def harness_results(version):
    """platform to `passed/total`, for one version."""
    out = {}
    for line in (version or {}).get("harness", []) or []:
        platform, _, ratio = line.partition(": ")
        out[platform] = ratio
    return out


def used_platforms(doc):
    """Every platform anything in the index mentions, in the canonical order."""
    seen = set()
    for entry in doc.get("plugins", []):
        for version in entry.get("versions") or []:
            seen.update(version.get("platforms") or [])
            seen.update(harness_results(version))
    return [p for p in PLATFORMS if p in seen]


def runnable(entry, core):
    """The newest listed version this core would install, or None."""
    for version in reversed(entry.get("versions") or []):
        if core["compatible"] <= version.get("api", 0) <= core["api"]:
            return version
    return None


# ---------------------------------------------------------------------------
# Writing, one function per section
# ---------------------------------------------------------------------------


def table(headers, rows):
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return lines


def header_section(doc):
    return [
        GENERATED,
        "",
        "# Compatibility",
        "",
        "%s, run by %s. %d plugins are listed."
        % (doc.get("title", doc.get("name")), doc.get("owner", "nobody in particular"), len(doc.get("plugins", []))),
        "",
        "Every number on this page came out of the conformance harness on a CI runner,",
        "not out of a claim in a pull request. Eight checks run per platform, so a result",
        "reads `8/8` when a plugin did everything a plugin of its kind has to do. A blank",
        "cell means nobody has run it there yet, which is not the same as a failure and is",
        "not treated as one.",
        "",
    ]


def cores_section(doc):
    cores = doc.get("cores") or []
    if not cores:
        return []
    rows = [
        (
            "`%s`" % core["version"],
            str(core["api"]),
            "%d to %d" % (core["compatible"], core["api"]),
        )
        for core in cores
    ]
    return [
        "## Cores",
        "",
        "A core runs a plugin when the plugin's declared api level falls inside the range",
        "the core reads. Nothing else about the core versions matters to a listing.",
        "",
    ] + table(["Core", "API level", "Reads API"], rows) + [""]


def listings_section(doc):
    rows = []
    for entry in sorted_plugins(doc):
        version = newest(entry) or {}
        rows.append(
            (
                "`%s`" % entry.get("name", "?"),
                entry.get("tier", "custom"),
                "`%s`" % version.get("version", "none"),
                str(version.get("api", "")),
                "yes" if version.get("signed") else "no",
                ", ".join(entry.get("kinds") or []) or "none",
                "`%s`" % entry.get("source", ""),
            )
        )
    return [
        "## Listings",
        "",
        "Newest version of each plugin, highest tier first. `Signed` is whether this",
        "index's CI signed that version's assets with the identity in the signing block.",
        "",
    ] + table(["Plugin", "Tier", "Version", "API", "Signed", "Kinds", "Source"], rows) + [""]


def harness_section(doc):
    platforms = used_platforms(doc)
    rows = []
    for entry in sorted_plugins(doc):
        for version in entry.get("versions") or []:
            results = harness_results(version)
            declared = version.get("platforms") or []
            cells = []
            for platform in platforms:
                if platform in results:
                    cells.append("`%s`" % results[platform])
                elif platform in declared:
                    cells.append("shipped, not run")
                else:
                    cells.append(" ")
            rows.append(("`%s`" % entry.get("name", "?"), "`%s`" % version.get("version", "?")) + tuple(cells))
    return [
        "## Harness results",
        "",
        "Every version of every listing, and what the harness recorded on each platform.",
        "`shipped, not run` means the version publishes an asset for that platform and no",
        "result has been recorded for it, which is what keeps a listing at bronze.",
        "",
    ] + table(["Plugin", "Version"] + platforms, rows) + [""]


def resolution_section(doc):
    cores = doc.get("cores") or []
    if not cores:
        return []
    rows = []
    for entry in sorted_plugins(doc):
        cells = []
        for core in cores:
            version = runnable(entry, core)
            cells.append("`%s`" % version["version"] if version else "nothing listed")
        rows.append(("`%s`" % entry.get("name", "?"),) + tuple(cells))
    return [
        "## What each core installs",
        "",
        "`gmx plugin add <name>` takes the newest listed version whose api the running",
        "core reads. This is that answer, worked out for every core release above.",
        "",
    ] + table(["Plugin"] + ["Core %s" % c["version"] for c in cores], rows) + [""]


def footer_section(doc):
    return [
        "## Reading a tier",
        "",
        "* `custom` was listed and nothing was checked. It runs with the permissions you give it.",
        "* `bronze` validates, passes the harness on one platform, has a SKILL.md and a release.",
        "* `silver` passes on every platform it declares, and its code owner answers inside a month.",
        "* `gold` has two or more maintainers, an eval suite with recorded shows, and reviewed docs.",
        "",
        "README.md carries the whole scale and what each tier has to prove.",
        "",
    ]


def render(doc):
    lines = []
    for section in (
        header_section,
        cores_section,
        listings_section,
        harness_section,
        resolution_section,
        footer_section,
    ):
        lines.extend(section(doc))
    return "\n".join(lines).rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# The command line
# ---------------------------------------------------------------------------


def main(argv=None):
    parser = argparse.ArgumentParser(description="Write compatibility.md out of index.json.")
    parser.add_argument("--index", default=DEFAULT_INDEX, help="the index document to read")
    parser.add_argument("--out", default=DEFAULT_OUT, help="the dashboard to write")
    parser.add_argument("--check", action="store_true", help="do not write; fail when the file on disk is not what this would write")
    args = parser.parse_args(argv)

    text = render(load(args.index))

    if args.check:
        try:
            with open(args.out, "r", encoding="utf-8") as f:
                on_disk = f.read()
        except OSError:
            on_disk = ""
        if on_disk != text:
            print("FAIL %s is not what bot/dashboard.py writes. Run it and commit the result." % os.path.basename(args.out))
            return 1
        print("ok   %s is up to date" % os.path.basename(args.out))
        return 0

    with open(args.out, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote %s, %d lines" % (args.out, text.count("\n")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
