// The designer kits, typed.
//
// The reference implementation is plain ES modules in ui/kits, the Python
// library has its own copy, and this is the third. Three copies of one
// algorithm drift, so the behaviour has a single source of truth:
// ui/kits/fixtures.json, generated by dev/kit-fixtures.mjs from the reference
// modules and replayed by test/kits.test.ts against everything below.
//
//   import { kits } from "@godwinmix/client";
//
//   const handles = kits.handlesFor(box, kits.gizmosFor(plugin.designer));
//   const drag = kits.applyDrag(handles[4], { box, transform }, dx, dy, {});
//   await client.call("scene.item.set", { item, props: drag.props });
//
// Nothing in here touches a DOM, a socket or a timer, so the same code runs in
// a browser, in node and in a worker. The browser-only halves of the reference
// kits, the 2D drawing in ui/kits/canvas/draw.js and the widgets in
// ui/kits/schema/render.js, are deliberately not ported: a surface draws with
// whatever it draws with, and the arithmetic that decides what to draw is here.

export * from "./protocol.ts";
export * from "./canvas.ts";
export * from "./schema.ts";
