// The designer kits, against the one recorded contract.
//
// ui/kits/fixtures.json is generated by dev/kit-fixtures.mjs: it runs the
// reference kit in ui/kits over a list of inputs and writes down exactly what
// it answered. This file replays the same inputs through the TypeScript port
// and asserts the same answers, case by case, section by section.
//
// It does that twice over. The first pass compares the port with the recorded
// answers, which is the check that still works when the repository is gone and
// only the fixture file travels. The second pass drives the port and the
// browser modules in ui/kits over the same cases in one run and asserts they
// agree, which catches a reference kit that has moved on without the fixtures
// being regenerated.
//
// The cross check lives here rather than in parity.test.ts because every case
// runner, the kit adapter and the rounding helper are already in this file, and
// parity.test.ts is about ui/client: a second copy of this machinery over there
// would be the exact duplication these fixtures exist to prevent.
//
// Everything is rounded to two decimal places first, the way dev/kit-fixtures
// .mjs rounds it, so a port that computes in a different order is not failed by
// the last bit of a double.

import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, it } from "node:test";

import { kits } from "../src/index.ts";

const KITS = fileURLToPath(new URL("../../../ui/kits/", import.meta.url));
const present = existsSync(KITS + "fixtures.json");
const fixtures: any = present ? JSON.parse(readFileSync(KITS + "fixtures.json", "utf8")) : null;

/** The slice of a kit the fixtures exercise, in either language. */
interface Kit {
  SceneMirror: new (opts: { clientId?: string | null }) => any;
  Prediction: new () => any;
  mergeProps(base: any, next: any): any;
  gizmosFor(designer: any): any[];
  handlesFor(box: any, gizmos: any[]): any[];
  applyDrag(handle: any, start: any, dx: number, dy: number, mods: any): any;
  snapTargets(what: any): any;
  snapDelta(box: any, targets: any, opts: any): any;
  safeAreas(canvas: any): any;
  describeForm(schema: any, value: any): any;
  valuesOf(form: any): any;
  readForm(form: any, values: any, touched: Set<string>): any;
  missing(form: any, values: any): string[];
  layoutFor(form: any, ui: any): any;
  applyRules(layout: any, values: any): any;
  controlsOf(layout: any): any[];
}

const ours = kits as unknown as Kit;

/** The same modules, as the reference UI loads them. */
async function browserKit(): Promise<Kit> {
  const [mirror, predict, gizmos, snap, safe, data, ui] = await Promise.all([
    import(KITS + "protocol/mirror.js"),
    import(KITS + "protocol/predict.js"),
    import(KITS + "canvas/gizmos.js"),
    import(KITS + "canvas/snap.js"),
    import(KITS + "canvas/safe.js"),
    import(KITS + "schema/describe.js"),
    import(KITS + "schema/ui-schema.js"),
  ]);
  return {
    SceneMirror: mirror.SceneMirror,
    Prediction: predict.Prediction,
    mergeProps: predict.mergeProps,
    gizmosFor: gizmos.gizmosFor,
    handlesFor: gizmos.handlesFor,
    applyDrag: gizmos.applyDrag,
    snapTargets: snap.snapTargets,
    snapDelta: snap.snapDelta,
    safeAreas: safe.safeAreas,
    describeForm: data.describeForm,
    valuesOf: data.valuesOf,
    readForm: data.readForm,
    missing: data.missing,
    layoutFor: ui.layoutFor,
    applyRules: ui.applyRules,
    controlsOf: ui.controlsOf,
  };
}

// ------------------------------------------------------- one case per section

function mirrorCase(kit: Kit, c: any): unknown {
  const mirror = new kit.SceneMirror({ clientId: c.clientId });
  const steps: unknown[] = [];
  for (const step of c.steps) {
    if (step.view) {
      mirror.applyView(step.view);
      steps.push({ kind: "view" });
    } else {
      const r = mirror.applyPatch(step.patch);
      steps.push({ kind: "patch", applied: r.applied, echo: r.echo, gap: r.gap, seq: r.seq });
    }
  }
  const scenes = mirror.scenes();
  return {
    steps,
    seq: mirror.seq,
    unknown: mirror.unknown,
    scenes: scenes.map((s: any) => s.id),
    items: Object.fromEntries(scenes.map((s: any) => [s.id, mirror.items(s.id).map((i: any) => i.id)])),
    names: Object.fromEntries(
      [...mirror.records.values()].map((r: any) => [r.id, r.name === undefined ? null : r.name]),
    ),
  };
}

function predictCase(kit: Kit, c: any): unknown {
  const p = new kit.Prediction();
  const seqs: number[] = [];
  const settled: string[][] = [];
  for (const [op, a, b] of c.ops) {
    if (op === "predict") seqs.push(p.predict(a, b));
    else settled.push(p.settle(a));
  }
  return {
    seqs,
    settled,
    acked: p.acked,
    pending: [...p.pending.keys()].sort(),
    resolved: Object.fromEntries(
      Object.entries(c.resolve || {}).map(([item, server]) => [item, p.resolve(item, server)]),
    ),
    accepted: (c.accepts || []).map(([item, echo]: [string, number]) => p.accepts(item, echo)),
  };
}

function gizmoCase(kit: Kit, c: any): unknown {
  return kit
    .gizmosFor(c.designer)
    .map((g) => ({ kind: g.kind, action: g.action, target: g.target, anchor: g.anchor }));
}

function handleCase(kit: Kit, c: any): unknown {
  return kit
    .handlesFor(c.box, kit.gizmosFor(c.designer))
    .map((h) => ({ kind: h.kind, action: h.action, x: r2(h.x), y: r2(h.y), dir: h.dir, cursor: h.cursor }));
}

function dragCase(kit: Kit, c: any): unknown {
  const result = kit.applyDrag(c.handle, c.start, c.dx, c.dy, c.mods || {});
  return { props: round(result.props), box: result.box ? round(result.box) : null };
}

function snapCase(kit: Kit, c: any): unknown {
  const delta = kit.snapDelta(c.box, kit.snapTargets(c.targets), c.opts || {});
  return {
    dx: r2(delta.dx),
    dy: r2(delta.dy),
    guides: delta.guides.map((g: any) => ({ axis: g.axis, at: r2(g.at), span: g.span.map(r2) })),
  };
}

function schemaCase(kit: Kit, c: any): unknown {
  const form = kit.describeForm(c.schema, c.value || {});
  return {
    groups: form.groups,
    fields: form.fields.map((f: any) => ({
      name: f.name,
      kind: f.kind,
      group: f.group,
      required: f.required,
      visible: f.visible,
      unit: f.unit === undefined ? null : f.unit,
      value: f.value === undefined ? null : f.value,
      choices: f.choices ? f.choices.map((x: any) => x.value) : null,
    })),
  };
}

/**
 * What the form sends and what it still wants. `values` is what the controls
 * hold, laid over the defaults the schema supplied, which is what a surface has
 * in its hand when the operator presses Save.
 */
function readCase(kit: Kit, c: any): unknown {
  const form = kit.describeForm(c.schema, c.value || {});
  const values = Object.assign({}, kit.valuesOf(form), c.values || {});
  return {
    read: kit.readForm(form, values, new Set<string>(c.touched || [])),
    missing: kit.missing(form, values),
  };
}

function uiCase(kit: Kit, c: any): unknown {
  const form = kit.describeForm(c.schema, c.value || {});
  const layout = kit.applyRules(kit.layoutFor(form, c.ui), kit.valuesOf(form));
  return {
    controls: kit.controlsOf(layout).map((n: any) => ({
      field: n.field.name,
      control: n.control,
      visible: n.visible !== false,
      enabled: n.enabled !== false,
    })),
  };
}

/** Section name to the function that produces one case's `out` block. */
const SECTIONS: Record<string, (kit: Kit, c: any) => unknown> = {
  mirror: mirrorCase,
  predict: predictCase,
  merge: (kit, c) => kit.mergeProps(c.base, c.next),
  gizmos: gizmoCase,
  handles: handleCase,
  drag: dragCase,
  snap: snapCase,
  safe: (kit, c) => round(kit.safeAreas(c.canvas)),
  schema: schemaCase,
  read: readCase,
  uiSchema: uiCase,
};

function r2(v: unknown): unknown {
  return typeof v === "number" ? Math.round(v * 100) / 100 : v;
}

function round(value: any): any {
  if (Array.isArray(value)) return value.map(round);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, round(v)]));
  }
  return r2(value);
}

function label(section: string, c: any, at: number): string {
  return `${section}[${at}] ${c.name || JSON.stringify(c.canvas || {})}`;
}

// ------------------------------------------------------------------ the runs

const why = present ? false : "no ui/kits in this tree";

describe("the kits answer what ui/kits/fixtures.json recorded", { skip: why }, () => {
  for (const [section, run] of Object.entries(SECTIONS)) {
    it(section, () => {
      const cases = fixtures[section];
      assert.ok(Array.isArray(cases) && cases.length, `${section} has no cases`);
      cases.forEach((c: any, at: number) => {
        assert.deepEqual(run(ours, c), c.out, label(section, c, at));
      });
    });
  }
});

describe("the TypeScript kit and the browser kit agree", { skip: why }, () => {
  it("over every fixture, in one run", async () => {
    const theirs = await browserKit();
    for (const [section, run] of Object.entries(SECTIONS)) {
      fixtures[section].forEach((c: any, at: number) => {
        assert.deepEqual(run(ours, c), run(theirs, c), label(section, c, at));
      });
    }
  });
});

// ------------------------------------------- the parts no fixture case reaches
//
// The fixtures cover the arithmetic three languages share. What is left is the
// glue: an undo proxy that only needs an object with a `call` method, the view
// transform, the geometry index and the renderer ranking. Those are checked
// here so the port is not carried by the fixtures alone.

describe("the kit parts the fixtures do not reach", () => {
  it("folds a batch of edits into one undo step", async () => {
    const calls: Array<[string, unknown]> = [];
    const pushed: any[] = [];
    const proxy = new kits.UndoProxy(
      { call: async (m, p) => (calls.push([m, p]), { steps: 1 }) },
      { push: (e) => pushed.push(e) },
    );

    const answer = await proxy.group("Move 3 items", async () => "done", { offer: true });
    assert.equal(answer, "done");
    assert.deepEqual(
      calls.map(([m]) => m),
      ["scene.history.mark", "scene.history.mark"],
    );
    assert.deepEqual(calls[0]![1], { label: "Move 3 items" });
    assert.deepEqual(calls[1]![1], {});
    assert.equal(pushed.length, 1);
    assert.equal(pushed[0].label, "Move 3 items");
    assert.equal(pushed[0].offer, true);

    await pushed[0].undo();
    assert.equal(calls[2]![0], "scene.undo");
  });

  it("stops asking a core with no history", async () => {
    const stack = { push: () => {} };
    const proxy = new kits.UndoProxy(
      {
        call: async () => {
          throw Object.assign(new Error("no such method"), { code: -32601 });
        },
      },
      stack,
    );
    await proxy.mark("Rename");
    assert.equal(proxy.available, false);
  });

  it("indexes the geometry a view answered with", () => {
    const index = kits.geometryIndex({
      id: "s1",
      records: [],
      geometry: [{ item: "i1", x: 0 }, { item: "i2", x: 10 }],
    });
    assert.equal(index.size, 2);
    assert.equal(index.get("i2")!["x"], 10);
  });

  it("maps canvas pixels to a letterboxed surface and back", () => {
    const view = new kits.View({ width: 1920, height: 1080 }, { width: 960, height: 1080 });
    assert.equal(view.scale, 0.5);
    assert.equal(view.offsetX, 0);
    assert.equal(view.offsetY, 270);
    const p = view.toSurface(1920, 1080);
    assert.deepEqual(p, { x: 960, y: 810 });
    assert.deepEqual(view.toCanvas(p.x, p.y), { x: 1920, y: 1080 });
    assert.equal(view.lengthFromSurface(8), 16);
  });

  it("reads a rectangle back out of a transform and in again", () => {
    const transform = {
      position: { x: 480, y: 270 },
      frame: { w: 960, h: 540 },
      anchor: { x: 0.5, y: 0.5 },
      scale: { x: 1, y: 1 },
    };
    const box = kits.itemRect(transform, { width: 1920, height: 1080 });
    assert.deepEqual(box, { x: 0, y: 0, width: 960, height: 540 });
    assert.deepEqual(kits.rectToTransform(box, transform), {
      frame: { w: 960, h: 540 },
      position: { x: 480, y: 270 },
    });
  });

  it("finds the nearest handle and never the cage", () => {
    const box = { x: 0, y: 0, width: 400, height: 200 };
    const handles = kits.handlesFor(box, kits.gizmosFor(null));
    assert.equal(kits.hitTest(handles, 200, 100, 12), null);
    const corner = kits.hitTest(handles, 402, 202, 12);
    assert.equal(corner!.kind, "corner");
    assert.deepEqual(corner!.dir, [1, 1]);
  });

  it("writes and reads a dotted path", () => {
    const props = kits.pathProps("params.key_tolerance", 0.4);
    assert.deepEqual(props, { params: { key_tolerance: 0.4 } });
    assert.equal(kits.pathValue(props, "params.key_tolerance"), 0.4);
    assert.equal(kits.pathValue(props, "params.missing"), undefined);
    assert.deepEqual(kits.pathProps("", 1), {});
  });

  it("spaces ruler ticks at a number a person reads", () => {
    assert.deepEqual(kits.ticks(400, 1, 80), [0, 100, 200, 300, 400]);
    assert.deepEqual(kits.ticks(40, 8, 80), [0, 10, 20, 30, 40]);
  });

  it("boxes a selection and reports overlap", () => {
    const a = { x: 0, y: 0, width: 10, height: 10 };
    const b = { x: 20, y: 20, width: 10, height: 10 };
    assert.deepEqual(kits.unionOf([a, b]), { x: 0, y: 0, width: 30, height: 30 });
    assert.equal(kits.unionOf([]), null);
    assert.equal(kits.overlaps(a, b), false);
    assert.equal(kits.overlaps(a, { x: 5, y: 5, width: 10, height: 10 }), true);
    assert.equal(kits.inside(a, 5, 5), true);
    assert.deepEqual(kits.rectFrom(10, 10, 0, 4), { x: 0, y: 4, width: 10, height: 6 });
  });

  it("resolves a plugin's own snap point inside the item's box", () => {
    const item = { params: { anchor_point: { x: 0.5, y: 1 } } };
    const box = { x: 100, y: 100, width: 400, height: 200 };
    assert.deepEqual(kits.pointsOf(item, box, { points: ["params.anchor_point"] }), [{ x: 300, y: 300 }]);
    assert.deepEqual(kits.pointsOf(item, box, { points: ["params.missing"] }), []);
  });

  it("reads the sequence number a patch echoes back, whatever it is called", () => {
    assert.equal(kits.echoSeqOf({ client_seq: 4 }), 4);
    assert.equal(kits.echoSeqOf({ echo_seq: 5 }), 5);
    assert.equal(kits.echoSeqOf({ seq_echo: 6 }), 6);
    assert.equal(kits.echoSeqOf(null), 0);
  });

  it("gives the highest ranked renderer the control, and the last one the tie", () => {
    const form = kits.describeForm({ type: "object", properties: { key: { type: "string" } } }, {});
    const layout = kits.layoutFor(form, null);
    const registry = new kits.Renderers<string, null>();

    kits.registerTable(registry, { text: () => "kit text" });
    assert.deepEqual(registry.explain(layout), { key: "text" });

    const off = registry.register({ name: "host colour", test: () => kits.HOST, make: () => "picker" });
    assert.deepEqual(registry.explain(layout), { key: "host colour" });
    off();
    assert.deepEqual(registry.explain(layout), { key: "text" });

    registry.register({ name: "never", test: () => 0, make: () => "no" });
    const control = kits.controlsOf(layout)[0]!;
    assert.equal(registry.pick(control)!.rank, kits.BASE);
    assert.throws(() => registry.register({ name: "broken" } as any), /test and a make/);
  });

  it("declares a control the data schema could not have guessed", () => {
    const field = { name: "key", label: "Key", kind: "text", group: "", required: false, value: undefined, visible: true };
    assert.equal(kits.controlFor(field as any, "template.chroma"), "template.chroma");
    assert.equal(kits.controlFor(field as any, "no-such-control"), "text");
    assert.equal(kits.fieldOfScope("#/properties/gain"), "gain");
    assert.equal(kits.fieldOfScope("gain"), "gain");
    assert.equal(kits.fieldOfScope(null), null);
  });
});
